TAG = (RC DASH BRANCH DASH)? VERSION (DASH REVISION)?;

BRANCH = (#"\w"+ (DOT | DASH | '_' | '/')? #"\w")+;

VERSION = V VERSION_NUMBER DOT VERSION_NUMBER DOT VERSION_NUMBER;
RC = 'rc';
V = 'v';
<DOT> = '.';
<DASH> = '-';
ZERO = '0';
ONE_TO_NINE = #"[1-9]";
VERSION_NUMBER = ZERO | ONE_TO_NINE (ZERO | ONE_TO_NINE)*
REVISION = #"[0-9a-f]"+
